TMVAxml: bdtWeights/TMVAClassification_BDT.weights.xml
OutputDir: test-l1PFTau
ProjectName: l1PFTau
XilinxPart: xc7vx690tffg1927-2
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
ReuseFactor: 1
DefaultPrecision: ap_fixed<18,8> 
